# backend/alembic/script.py.mako
"""add_model_configs_table

Revision ID: 0ce3101355a6
Revises: 003
Create Date: 2026-04-22 14:34:38.631528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce3101355a6'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('health_latency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_id'), 'model_configs', ['id'], unique=False)
    op.drop_index(op.f('ix_agent_prompts_user_id'), table_name='agent_prompts')
    op.create_index(op.f('ix_agent_prompts_id'), 'agent_prompts', ['id'], unique=False)
    op.drop_index(op.f('ix_project_agent_prompts_project_id'), table_name='project_agent_prompts')
    op.create_index(op.f('ix_project_agent_prompts_id'), 'project_agent_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_agent_prompts_id'), table_name='project_agent_prompts')
    op.create_index(op.f('ix_project_agent_prompts_project_id'), 'project_agent_prompts', ['project_id'], unique=False)
    op.drop_index(op.f('ix_agent_prompts_id'), table_name='agent_prompts')
    op.create_index(op.f('ix_agent_prompts_user_id'), 'agent_prompts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_model_configs_id'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###