# backend/alembic/script.py.mako
"""add_provider_type_and_models

Revision ID: 8d29d8d632e5
Revises: 20260424_remove_workflow
Create Date: 2026-04-24 14:18:48.629671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d29d8d632e5'
down_revision: Union[str, None] = '20260424_remove_workflow'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 provider_type 和 models 字段到 model_configs 表
    op.add_column('model_configs', sa.Column('provider_type', sa.String(length=20), nullable=True))
    op.add_column('model_configs', sa.Column('models', sa.JSON(), nullable=True))

    # 设置默认值：现有配置都是单模型类型
    op.execute("UPDATE model_configs SET provider_type = 'single' WHERE provider_type IS NULL")

    # 设置非空约束
    op.alter_column('model_configs', 'provider_type', nullable=False)

    # model_name 改为可空（多模型配置时可以为空）
    op.alter_column('model_configs', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # 删除旧索引（将被新索引替代）
    op.drop_index(op.f('idx_model_configs_user_default'), table_name='model_configs', postgresql_where='(is_default = true)')

    # 删除 projects 表中已迁移到 workflow_states 的工作流字段
    op.drop_column('projects', 'stage')
    op.drop_column('projects', 'review_mode')
    op.drop_column('projects', 'max_rewrite_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢复 projects 表中的工作流字段
    op.add_column('projects', sa.Column('max_rewrite_count', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('review_mode', sa.VARCHAR(length=20), server_default=sa.text("'off'::character varying"), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # 恢复索引
    op.create_index(op.f('idx_model_configs_user_default'), 'model_configs', ['user_id'], unique=True, postgresql_where='(is_default = true)')

    # model_name 恢复为非空
    op.alter_column('model_configs', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # 删除新添加的字段
    op.drop_column('model_configs', 'models')
    op.drop_column('model_configs', 'provider_type')
    # ### end Alembic commands ###