# backend/alembic/script.py.mako
"""add agent conversations and messages

Revision ID: ae95e3f489f1
Revises: 20260523_busy
Create Date: 2026-05-25 08:57:11.865125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae95e3f489f1'
down_revision: Union[str, None] = '20260523_busy'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_agent_conversations_id'), 'agent_conversations', ['id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_agent_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_conversation_id'), 'agent_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.alter_column('arcs', 'outline_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('model_configs', 'context_window',
               existing_type=sa.INTEGER(),
               comment='模型上下文窗口大小（token 数），NULL 表示使用默认映射',
               existing_comment='模型上下文窗口大小（token 数）',
               existing_nullable=True)
    op.alter_column('projects', 'is_busy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'is_busy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('model_configs', 'context_window',
               existing_type=sa.INTEGER(),
               comment='模型上下文窗口大小（token 数）',
               existing_comment='模型上下文窗口大小（token 数），NULL 表示使用默认映射',
               existing_nullable=True)
    op.alter_column('arcs', 'outline_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_conversation_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_conversations_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###