"""Outline schemas"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel


class CollectedInfo(BaseModel):
    """Collected information from user"""

    genre: Optional[str] = None
    theme: Optional[str] = None
    main_characters: Optional[str] = None
    world_setting: Optional[str] = None
    style_preference: Optional[str] = None


# v0.6.1: 情节节点增强结构
class PlotPoint(BaseModel):
    """情节节点"""

    order: int = 0
    event: str = ""
    conflict: Optional[str] = None
    hook: Optional[str] = None


# v0.6.1: 人物设定结构
class Character(BaseModel):
    """人物设定"""

    name: str = ""
    role: str = ""
    personality: Optional[str] = None
    motivation: Optional[str] = None
    arc: Optional[str] = None


# v0.6.1: 世界观设定结构
class WorldSetting(BaseModel):
    """世界观设定"""

    era: Optional[str] = None
    core_rules: Optional[str] = None
    power_system: Optional[str] = None


class OutlineBase(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    plot_points: Optional[list[dict]] = None  # v0.6.1: 改为 dict 列表
    characters: Optional[list[dict]] = None  # v0.6.1: 人物设定
    world_setting: Optional[dict] = None  # v0.6.1: 世界观
    emotional_curve: Optional[str] = None  # v0.6.1: 情感曲线
    collected_info: Optional[dict] = None
    inspiration_template: Optional[str] = None


class OutlineCreate(BaseModel):
    pass  # Generated by AI


class OutlineUpdate(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    plot_points: Optional[list[dict]] = None  # v0.6.1: 改为 dict 列表
    characters: Optional[list[dict]] = None  # v0.6.1: 人物设定
    world_setting: Optional[dict] = None  # v0.6.1: 世界观
    emotional_curve: Optional[str] = None  # v0.6.1: 情感曲线
    collected_info: Optional[dict] = None
    inspiration_template: Optional[str] = None


class OutlineResponse(OutlineBase):
    id: int
    project_id: int
    chapter_count_suggested: int
    chapter_count_confirmed: bool
    confirmed: bool
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class ChapterCountRequest(BaseModel):
    chapter_count: int


class ChatMessage(BaseModel):
    """Chat message for info collection"""

    message: str


class ChatResponse(BaseModel):
    """Chat response from agent"""

    response: str
    collected_info: Optional[CollectedInfo] = None
    is_info_sufficient: bool = False


class CollectedInfoUpdate(BaseModel):
    """灵感收集信息更新"""

    # 原有字段
    genre: Optional[str] = None
    theme: Optional[str] = None
    main_characters: Optional[str] = None
    world_setting: Optional[str] = None
    style_preference: Optional[str] = None
    # 新增灵感采集字段
    novelType: Optional[str] = None
    targetWords: Optional[int] = None
    coreTheme: Optional[str] = None
    targetReader: Optional[str] = None
    era: Optional[str] = None
    wordsPerChapter: Optional[str] = None
    customWordsPerChapter: Optional[int] = None
    maleLead: Optional[str] = None
    customMaleLead: Optional[str] = None
    femaleLead: Optional[str] = None
    customFemaleLead: Optional[str] = None
    protagonist: Optional[str] = None
    narrative: Optional[str] = None
    goldFinger: Optional[str] = None
    customGoldFinger: Optional[str] = None
    customGenre: Optional[str] = None
    customWorldSetting: Optional[str] = None
    inspiration_template: Optional[str] = None


