"""Outline schemas"""

from datetime import datetime
from typing import Optional, Any
from pydantic import BaseModel


class CollectedInfo(BaseModel):
    """Collected information from user"""
    genre: Optional[str] = None
    theme: Optional[str] = None
    main_characters: Optional[str] = None
    world_setting: Optional[str] = None
    style_preference: Optional[str] = None


class OutlineBase(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    plot_points: Optional[list[str]] = None
    collected_info: Optional[dict] = None
    inspiration_template: Optional[str] = None


class OutlineCreate(BaseModel):
    pass  # Generated by AI


class OutlineUpdate(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    plot_points: Optional[list[str]] = None
    collected_info: Optional[dict] = None
    inspiration_template: Optional[str] = None


class OutlineResponse(OutlineBase):
    id: int
    project_id: int
    chapter_count_suggested: int
    chapter_count_confirmed: bool
    confirmed: bool
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class ChapterCountRequest(BaseModel):
    chapter_count: int


class ChatMessage(BaseModel):
    """Chat message for info collection"""
    message: str


class ChatResponse(BaseModel):
    """Chat response from agent"""
    response: str
    collected_info: Optional[CollectedInfo] = None
    is_info_sufficient: bool = False


class CollectedInfoUpdate(BaseModel):
    """Update collected info directly"""
    genre: Optional[str] = None
    theme: Optional[str] = None
    main_characters: Optional[str] = None
    world_setting: Optional[str] = None
    style_preference: Optional[str] = None